force-app/main/default/objects/Contract/fields/Area_Acres__c.field-meta.xml
<CustomField>
    <fullName>Area_Acres__c</fullName>
    <label>Area Acres</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet__c</fullName>
    <description>Enter how big in square feet the job is going to be</description>
    <label>Square Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Event__e/Contract_Event__e.object-meta.xml
<CustomObject>
    <label>Contract Event</label>
    <pluralLabel>Contract Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contract_Event__e/fields/Active_Contract__c.field-meta.xml
<CustomField>
    <fullName>Active_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether the contract is newly created and has passed the draft process</description>
    <label>Active Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Event__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Assignment__c/Site_Assignment__c.object-meta.xml
<CustomObject>
    <label>Site Assignment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Site Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataHelper.cls
@isTest
public class TestDataHelper {
    
    public static User createTestUser(String profileName) {
        Id profileId = [SELECT Id FROM Profile WHERE Name=:profileName LIMIT 1].Id;
        User test_user = new User();
        test_user.Alias = 'test';
        test_user.Email = 'test@testy.com';
        test_user.FirstName = 'test';
        test_user.LastName = 'testy';
        test_user.ProfileId = profileId;
        test_user.Username = 'asdfghdhfgawefasdc@testtest.com';
        test_user.TimeZoneSidKey = 'America/Los_Angeles';
        test_user.LanguageLocaleKey='en_US';
        test_user.LocaleSidKey = 'en_US';
        test_user.EmailEncodingKey = 'UTF-8';

        Insert test_user;
        return test_user;
    }

    public static List<Site_Assignment__c> createSiteJunctionObject(Integer numSiteJunction) {
        List<Site_Assignment__c> site_junctions = new List<Site_Assignment__c>();
        for (Integer i =0; i < numSiteJunction; i++) {
            site_junctions.add(new Site_Assignment__c());
        }
        return site_junctions;
    }

    public static List<Contract> createContractsWithSquareFeet(Integer numContracts) {
        List<Contract> contractList = new List<Contract>();

        for(Integer i = 0; i<numContracts; i++) {
            contractList.add(new Contract(name = 'Contract' + i, Square_Feet__c = 43560));
        }
        return contractList;
    }

    public static List<Contract> createContractsWithAreaAcres(Integer numContracts) {
        List<Contract> contractList = new List<Contract>();

        for(Integer i = 0; i<numContracts; i++) {
            contractList.add(new Contract(name = 'Contract' + i, Area_Acres__c = 0.0000229568));
        }
        return contractList;
    }
    
    public static List<Contract_Event__e> createEvents(Integer numEvents) {
        List<Contract_Event__e> event_list = new List<Contract_Event__e>();
        for (Integer i = 0; i < numEvents; i++) {
            event_list.add(buildContractEvent(null, true));
        }
        return event_list;
    }
    
    public static Contract_Event__e buildContractEvent(String description, Boolean active) {
        Contract_Event__e newEvent = new Contract_Event__e();
        newEvent.Description__c = description;
        newEvent.Active_Contract__c = active;
        return newEvent;
    }
}