force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Assignment__c/Site_Assignment__c.object-meta.xml
<CustomObject>
    <label>Site Assignment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Site Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Assignment__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Site Assignments</relationshipLabel>
    <relationshipName>Site_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SiteDetailControllerTest.cls
@isTest
public class SiteDetailControllerTest {
    
    @testSetup
    public static void setupTests() {
        // Create Site
        Site__c site_to_insert = new Site__c(Name='Testing Site');
        Insert site_to_insert;
        
        // Create Site junction object
        Site_Assignment__c junction_object = new Site_Assignment__c(Site__c = site_to_insert.Id);
        Insert junction_object;
    }
    
    @isTest
    public static void testConstructorPositive() {
        Test.startTest();
        SiteDetailController controller = new SiteDetailController();
        Test.stopTest();
        System.assert(!controller.all_sites_list.isEmpty(), 'No sites retrieved from controller');
    }
}